export const CAR_CATALOG: Record<string, string[]> = {
  Audi: ['A1', 'A3', 'A4', 'A5', 'A6', 'Q2', 'Q3', 'Q5', 'Q7', 'TT'],
  BMW: ['Serie 1', 'Serie 2', 'Serie 3', 'Serie 4', 'Serie 5', 'X1', 'X3', 'X5', 'M2', 'M3'],
  BYD: ['Dolphin', 'Seagull', 'Yuan Plus', 'Song Plus', 'Han', 'Tang', 'Seal'],
  Changan: ['Alsvin', 'CS15', 'CS35', 'CS55', 'CS75', 'UNI-T', 'UNI-K'],
  Chery: ['Arrizo 5', 'Tiggo 2', 'Tiggo 3', 'Tiggo 4', 'Tiggo 7', 'Tiggo 8'],
  Chevrolet: ['Agile', 'Aveo', 'Camaro', 'Captiva', 'Corsa', 'Cruze', 'Onix', 'Prisma', 'S10', 'Spark', 'Tracker'],
  Citroen: ['Berlingo', 'C3', 'C4', 'C4 Cactus', 'C5 Aircross', 'Jumper'],
  Cupra: ['Formentor', 'Leon', 'Born', 'Ateca'],
  Daihatsu: ['Sirion', 'Terios', 'Mira'],
  Dodge: ['Attitude', 'Durango', 'Journey', 'RAM 1500'],
  DS: ['DS3', 'DS4', 'DS7'],
  Fiat: ['500', 'Argo', 'Cronos', 'Doblo', 'Fiorino', 'Mobi', 'Palio', 'Punto', 'Strada', 'Toro'],
  Ford: ['Bronco', 'EcoSport', 'Edge', 'Escape', 'Everest', 'Explorer', 'F-150', 'Fiesta', 'Focus', 'Ka', 'Maverick', 'Mustang', 'Ranger', 'Territory'],
  Foton: ['Tunland', 'View', 'Toano'],
  Geely: ['Coolray', 'Emgrand', 'Okavango', 'Geometry C'],
  GMC: ['Sierra', 'Yukon', 'Terrain'],
  GreatWall: ['Haval H2', 'Haval H6', 'Poer', 'Wingle'],
  Haval: ['H1', 'H2', 'H6', 'Jolion', 'Dargo'],
  Honda: ['Accord', 'BR-V', 'City', 'Civic', 'CR-V', 'Fit', 'HR-V', 'Odyssey', 'Pilot', 'Ridgeline'],
  Hyundai: ['Accent', 'Creta', 'Elantra', 'Grand i10', 'Santa Fe', 'Staria', 'Tucson', 'Veloster', 'Venue'],
  Infiniti: ['Q50', 'Q60', 'QX50', 'QX60', 'QX80'],
  Isuzu: ['D-Max', 'MU-X'],
  Iveco: ['Daily'],
  Jaguar: ['E-Pace', 'F-Pace', 'F-Type', 'XE', 'XF'],
  Jeep: ['Cherokee', 'Compass', 'Gladiator', 'Grand Cherokee', 'Renegade', 'Wrangler'],
  Kia: ['Carnival', 'Cerato', 'K3', 'K5', 'Morning', 'Niro', 'Picanto', 'Rio', 'Seltos', 'Sorento', 'Soul', 'Sportage', 'Stonic'],
  Lada: ['Niva', 'Granta'],
  LandRover: ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover Evoque', 'Range Rover Sport'],
  Lexus: ['ES', 'GX', 'IS', 'LS', 'LX', 'NX', 'RX', 'UX'],
  Mahindra: ['KUV100', 'Scorpio', 'XUV500'],
  Mazda: ['BT-50', 'CX-3', 'CX-30', 'CX-5', 'CX-9', 'Mazda2', 'Mazda3', 'MX-5'],
  MercedesBenz: ['A 200', 'C 200', 'CLA 200', 'E 300', 'GLA 200', 'GLC 300', 'GLE 450', 'Sprinter', 'Vito'],
  MG: ['MG3', 'MG5', 'MG ZS', 'MG HS', 'Marvel R'],
  Mini: ['Cooper', 'Countryman', 'Clubman'],
  Mitsubishi: ['ASX', 'Eclipse Cross', 'L200', 'Montero Sport', 'Outlander'],
  Nissan: ['370Z', 'Altima', 'Frontier', 'Juke', 'Kicks', 'Leaf', 'March', 'Murano', 'NP300', 'Pathfinder', 'Qashqai', 'Sentra', 'Versa', 'X-Trail'],
  Peugeot: ['2008', '208', '3008', '301', '308', '5008', 'Partner'],
  Porsche: ['718 Cayman', '911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
  RAM: ['700', '1200', '1500', '2500'],
  Renault: ['Captur', 'Clio', 'Duster', 'Kangoo', 'Koleos', 'Kwid', 'Logan', 'Megane', 'Oroch', 'Sandero', 'Stepway'],
  SEAT: ['Arona', 'Ateca', 'Ibiza', 'Leon', 'Toledo'],
  Skoda: ['Fabia', 'Kamiq', 'Karoq', 'Kodiaq', 'Octavia', 'Superb'],
  Subaru: ['BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Outback', 'WRX'],
  Suzuki: ['Alto', 'Baleno', 'Celerio', 'Dzire', 'Grand Vitara', 'Jimny', 'S-Cross', 'Swift', 'Vitara'],
  Tesla: ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck'],
  Toyota: ['4Runner', 'Corolla', 'Corolla Cross', 'Fortuner', 'Hilux', 'Land Cruiser', 'Prado', 'Prius', 'RAV4', 'Yaris'],
  Volkswagen: ['Amarok', 'Bora', 'Fox', 'Gol', 'Golf', 'Jetta', 'Nivus', 'Passat', 'Polo', 'T-Cross', 'Taos', 'Tiguan', 'Touareg', 'Vento', 'Virtus'],
  Volvo: ['C40', 'S60', 'S90', 'XC40', 'XC60', 'XC90']
};

export const CAR_BRANDS = Object.keys(CAR_CATALOG).sort((a, b) => a.localeCompare(b));
